model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 128

exp_params:
  dataset: celeba
  data_path: "/home/seuss/Research/FMEphys/"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_epochs: 30

logging_params:
  save_dir: "/home/seuss/Research/FMEphys/logs2/"
  name: "VanillaVAE"
  manual_seed: 1265
