model_params:
  name: 'ConditionalVAE'
  in_channels: 1
  num_classes: 0
  latent_dim: 128

exp_params:
  dataset: WorldCam
  data_path: "/home/seuss/Research/FMEphys/"
  csv_path_train: "/home/seuss/Research/FMEphys/WC_Train_Data.csv"
  csv_path_val: "/home/seuss/Research/FMEphys/WC_Val_Data.csv"
  imgH_size: 128
  imgW_size: 128  
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_epochs: 50

logging_params:
  save_dir: "/home/seuss/Research/FMEphys/logs/"
  name: "ConditionalVAE"
  manual_seed: 1265
