model_params:
  name: 'VAE3dmp'
  in_channels: 1
  latent_dim: 128
  depth_dim: 10
  xystrides: [2,2,2,2,2]
  tstrides: [1,1,1,1,1]
  kernels: [3,3,3,3,3]

exp_params:
  dataset: WorldCam3D
  data_path: "/home/seuss/Research/FMEphys/data/"
  csv_path_train: "/home/seuss/Research/FMEphys/WC3d_Train_Data.csv"
  csv_path_val: "/home/seuss/Research/FMEphys/WC3d_Val_Data.csv"
  imgH_size: 64
  imgW_size: 64
  batch_size: 1024 # 
  LR: 0.001
  weight_decay: 0.0
  scheduler_gamma: 1
  N_fm: 10

trainer_params:
  gpus: 1
  max_epochs: 500

logging_params:
  save_dir: "/home/seuss/Research/FMEphys/logs2/"
  name: "VAE3d"
  manual_seed: 1265
