model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 128

exp_params:
  dataset: WorldCam
  data_path: "/home/eabe/Research/FMEphys/"
  csv_path_train: "/home/eabe/Research/Github/PyTorch-VAE/WC_Train_Data.csv"
  csv_path_val: "/home/eabe/Research/Github/PyTorch-VAE/WC_Val_Data.csv"
  imgH_size: 128
  imgW_size: 128
  batch_size: 512 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_nb_epochs: 50
  max_epochs: 30

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"
  manual_seed: 1265
