model_params:
  name: 'VAE3dmp'
  in_channels: 1
  latent_dim: 5
  depth_dim: 32
  xystrides: [2,2,2,2,2]
  tstrides: [2,2,2,2,1]
  kernels: [5,5,5,5,5]
  mpkernels: [2,2,2,2,2]
  input_size: [16,128,128]
  hidden_dims: [16, 32, 64, 128, 256]

exp_params:
  dataset: Widefield3D
  data_path: "/mnt/data0/Niell/Widefield/G62FFF7TT"
  h5file: "aligned_bpf_dfof_100x100_G62FFF7TT.h5"
  img_size: 128
  imgH_size: 128
  imgW_size: 128
  batch_size: 32 
  LR: 0.001
  weight_decay: 0.0
  scheduler_gamma: 1
  N_fm: 32

trainer_params:
  gpus: 1
  max_epochs: 500

logging_params:
  save_dir: "/mnt/data0/Niell/Widefield/G62FFF7TT/VAE_outputs"
  name: "VAE3dmp"
  manual_seed: 1265
